# Top-level sections are targets. Call them whatever you want!
# If present, the 'default' section is always used.
[default]
	# What to run when the docker launches
	command = [ "/bin/echo", "Hello from docket!" ]

	# Custom DNS servers
	dns = [ "8.8.8.8", "8.8.4.4" ]

	# Folder mounts
	#	(host folder, container folder, 'ro' or 'rw' permissions)
	mounts = [
		[ ".../",           "/boxen", "ro"],  # The top folder
		[ "./",             "/cwd",   "ro"],  # The current folder
	]

	# What container folder to start in
	folder = "/"

	# Interactive mode
	attach = true

	# Delete the container after running
	purge = true

# An example of a different build target
# Using this, 'docket run bash' in any boxen folder to get an interactive shell.
[bash]
	# You can add or override any properties in targets.
	# Here, we run bash instead of just echo.
	command = [ "/bin/bash" ]

# Build target.
# By convention, a build target specifies an upstream image (absent here).
[build]
	# Our build command.
	# Most boxen scripts use the same command, so they do not need to specify this again.
	command = [ "/cwd/build.sh" ]
