# A largely unmodified Ubuntu box.
# We source from docker.io's public index, and clean apt-get state.

# This is where you name your image and its parent.
[image]
	# The image name.
	name = "index.docker.io/ubuntu/12.04"

	# Upstream ubuntu image, pulled from public docker index.
	#
	# The value of this configuration key is passed directly to 'docker pull'.
	# This lets you map index names to your own image names.
	#
	# Note: Namespacing in the public index works differently than full URL branch names.
	# As of Docker 0.6.3, the index pull behavior is incompatible with URLs.
	# Docker explicitly disallows specifying their own URL, see:
	# https://github.com/dotcloud/docker/blob/d30806/registry/registry.go#L100
	#
	index = "ubuntu:12.04"


# Don't need to specify any extra settings here.
# There were already a bunch set up in the parent folder's hroot.toml, and this file inherits them!
[settings]


# You can specify run targets of any name.
# Targets let you take different actions with the same container.

# This is the target that 'hroot run' will try if you don't specify one.
[target.run]
	command = [ "/bin/echo", "Hello from hroot!" ]

# This is the target that 'hroot build' will try if you don't specify one.
[target.build]
	command = [ "/hroot/build.sh" ]

# You can call targets anything, and they can have any command or extra settings.
# This target launches a bash shell - try 'hroot run bash' in this folder to try it out!
[target.bash]
	command = [ "/bin/bash" ]
