# Example nginx

[default]
	image = "docket.polydawn.net/nginx"

	# Run nginx in the foreground
	command = [ "/service/bin/nginx",  "-g", "daemon off;", "-c", "/service/conf/nginx.conf" ]

	# Port forwarding (host, guest)
	ports = [
		[  "80",  "80" ],
		[ "443", "443" ],
	]

	# Additional folder mounts
	mounts = [
		[ "./conf", "/service/conf", "ro" ],
		[ "./data", "/service/data", "ro" ],
		[ "./log",  "/service/log",  "rw" ],
	]

[build]
	# Use the dev-tools image to build nginx
	upstream = "docket.polydawn.net/dev-tools"
