# Example nginx

[image]
	# Image name
	name = "docket.polydawn.net/nginx"

	# This image is built from the dev-tools image, which is in turn built from ubuntu.
	upstream = "docket.polydawn.net/dev-tools"


[settings]
	# Port forwarding (host, guest)
	ports = [
		[  "80",  "80" ],
		[ "443", "443" ],
	]

	# Additional folder mounts
	mounts = [
		[ "./conf", "/service/conf", "ro" ],
		[ "./data", "/service/data", "ro" ],
		[ "./log",  "/service/log",  "rw" ],
	]


[targets]
	# Run nginx in the foreground
	[default]
		command = [ "/service/bin/nginx",  "-g", "daemon off;", "-c", "/service/conf/nginx.conf" ]

	[bash]
		command = [ "/bin/bash" ]

	[build]
		command = [ "/docket/build.sh" ]
