 # Example nginx

[image]
	# Image name
	name = "example.com/nginx"

	# This image is built from the dev-tools image, which is in turn built from ubuntu.
	upstream = "example.com/dev-tools"


[settings]
	# Additional folder mounts
	mounts = [
		[ "./log", "/service/log", "rw" ],
	]


[target.run]
	# Port forwarding (host, guest)
	ports = [
		[  "80",  "80" ],
		[ "443", "443" ],
	]

	# Run nginx in the foreground
	command = [ "/service/nginx",  "-g", "daemon off;", "-c", "/hroot/conf/nginx.conf" ]

[target.bash]
	command = [ "/bin/bash" ]

[target.build]
	command = [ "/hroot/build.sh" ]
