# Example nginx

[image]
	# Image name
	name = "example.com/nginx"

	# This image is built from the dev-tools image, which is in turn built from ubuntu.
	upstream = "example.com/dev-tools"


[settings]
	# Additional folder mounts
	mounts = [
		[ "./conf", "/service/conf", "ro" ],
		[ "./data", "/service/data", "ro" ],
		[ "./log",  "/service/log",  "rw" ],
	]


# Run nginx in the foreground
[target.run]
	# Port forwarding (host, guest)
	ports = [
		[  "80",  "80" ],
		[ "443", "443" ],
	]

	command = [ "/service/bin/nginx",  "-g", "daemon off;", "-c", "/service/conf/nginx.conf" ]

	# Port forwarding (host, guest)
	ports = [
		[  "80",  "80" ],
		[ "443", "443" ],
	]

[target.bash]
	command = [ "/bin/bash" ]

[target.build]
	command = [ "/bin/bash", "-c", "time /hroot/build.sh" ]
