# The default Ubuntu build.
# Docker's Ubuntu image + updates & a few tweaks.

# Run the build image.
[default]
	image = "docket.polydawn.net/public/ubuntu/12.04"

# Build target. Uses docker's Ubuntu image for upstream
[build]
	image = "index.docker.io/ubuntu/12.04"

	command = [ "/cwd/build.sh" ]
