# OpenLDAP directory server.

[default]
	image = "docket.polydawn.net/openldap"

	# Script to load
	command = [ "/cwd/run.sh" ]

	# Additional folder mounts
	mounts = [
		[ "./config/system", "/usr/share/slapd", "rw" ],
		[ "./config/schema", "/etc/ldap/schema", "rw" ],
		[ "./config/users",  "/service/users",   "rw" ],
	]

	# Port forwarding (host, guest)
	ports = [
		[ "389", "389" ]
	]

[build]
	upstream = "docket.polydawn.net/ubuntu/12.04"
