# OpenLDAP directory server.

[image]
	# Image name
	name = "docket.polydawn.net/openldap"

	# This image is built from the ubuntu image
	upstream = "docket.polydawn.net/ubuntu/12.04"


[settings]
	# Additional folder mounts
	mounts = [
		[ "./config/system", "/usr/share/slapd", "rw" ],
		[ "./config/schema", "/etc/ldap/schema", "rw" ],
		[ "./config/users",  "/service/users",   "rw" ],
	]

	# Port forwarding (host, guest)
	ports = [
		[ "389", "389" ]
	]


[targets]
	# Launcher script for openldap.
	[default]
		command = [ "/docket/run.sh" ]

	[bash]
		command = [ "/bin/bash" ]

	[build]
		command = [ "/docket/build.sh" ]
