# Common tools for developing web applications.

[image]
	# Image name
	name = "docket.polydawn.net/web-dev"

	# This image is built from the ubuntu image
	upstream = "docket.polydawn.net/ubuntu/12.04"


[settings]
	# Let node know where python is located
	environment = [
		[ "PYTHON", "/usr/bin/python2.7" ],
	]


# The web-dev image is for easily messing with common web tools, so the default target just launches a shell.
# This is copied into the bash target for consistency.
[target.run]
	command = [ "/bin/bash" ]

[target.bash]
	command = [ "/bin/bash" ]

[target.build]
	command = [ "/docket/build.sh" ]
