# Common tools for developing web applications.

# Run the build image.
[default]
	image = "pd-webdev:0.10.20"

	# Let node where python is located
	environment = [
		[ "PYTHON", "/usr/bin/python2.7" ],
	]

# Build target. Uses docker's Ubuntu image for upstream
[build]
	image = "ubuntu:12.10"

	command = [ "/cwd/build.sh" ]
