# Common tools for developing web applications.

[default]
	image = "pd-webdev:0.10.20"

	# Let node where python is located
	environment = [
		[ "PYTHON", "/usr/bin/python2.7" ],
	]

[build]
	image = "ubuntu:12.10" # Upstream image
