# Common tools for developing web applications.

[default]
	image = "docket.polydawn.net/web-dev"

	# Let node where python is located
	environment = [
		[ "PYTHON", "/usr/bin/python2.7" ],
	]

[build]
	upstream = "docket.polydawn.net/ubuntu/12.04"
