# Common tools for developing web applications.

# Run the build image.
[default]
	image = "docket.polydawn.net/public/webdev"

	# Let node where python is located
	environment = [
		[ "PYTHON", "/usr/bin/python2.7" ],
	]

# Build target. Uses docker's Ubuntu image for upstream
[build]
	image = "docket.polydawn.net/public/ubuntu/12.04"

	command = [ "/cwd/build.sh" ]
