# A few developer tools for building

[image]
	# Image name
	name = "docket.polydawn.net/dev-tools"

	# This image is built from the ubuntu image
	upstream = "docket.polydawn.net/ubuntu/12.04"


[settings]


[targets]
	# The dev-tools image is for commonly-required build packages, so the default target just launches a shell.
	# This is copied into the bash target for consistency.
	[default]
		command = [ "/bin/bash" ]

	[bash]
		command = [ "/bin/bash" ]

	[build]
		command = [ "/docket/build.sh" ]
