# A few developer tools for building

[image]
	# Image name
	name = "example.com/dev-tools"

	# This image is built from the ubuntu image
	upstream = "example.com/ubuntu/14.04"


[settings]


# The dev-tools image is for commonly-required build packages, so the default target just launches a shell.
# This is copied into the bash target for consistency.
[target.run]
	command = [ "/bin/bash" ]

[target.bash]
	command = [ "/bin/bash" ]

[target.build]
	command = [ "/hroot/build.sh" ]
